apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: app-with-submodule-example
spec:
  environments:
    - name: prod
      build:
        from: main
  components:
    - name: redis
      secrets:
        - REDIS_PASSWORD
      src: redis
      ports:
        - name: redis
          port: 6379